// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSk54iaqRcEbi0ChOD2U6Li6lqfUWI9Ic',
    appId: '1:1080265489076:web:db91e1a72ba756e6d1f5e1',
    messagingSenderId: '1080265489076',
    projectId: 'irischatproject',
    authDomain: 'irischatproject.firebaseapp.com',
    storageBucket: 'irischatproject.firebasestorage.app',
    databaseURL: 'https://irischatproject-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPaP2PIUM2dBxj7OQxtE8vcVn7sCh0wgg',
    appId: '1:1080265489076:android:69e978644242e04ad1f5e1',
    messagingSenderId: '1080265489076',
    projectId: 'irischatproject',
    storageBucket: 'irischatproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk6uBtf_nZuIeQqXvKl-smIZKq2xovttM',
    appId: '1:1080265489076:ios:4ab8ef4e9c3ae6d6d1f5e1',
    messagingSenderId: '1080265489076',
    projectId: 'irischatproject',
    storageBucket: 'irischatproject.firebasestorage.app',
    iosBundleId: 'com.example.irischat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk6uBtf_nZuIeQqXvKl-smIZKq2xovttM',
    appId: '1:1080265489076:ios:4ab8ef4e9c3ae6d6d1f5e1',
    messagingSenderId: '1080265489076',
    projectId: 'irischatproject',
    storageBucket: 'irischatproject.firebasestorage.app',
    iosBundleId: 'com.example.irischat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSk54iaqRcEbi0ChOD2U6Li6lqfUWI9Ic',
    appId: '1:1080265489076:web:7519662b13d31110d1f5e1',
    messagingSenderId: '1080265489076',
    projectId: 'irischatproject',
    authDomain: 'irischatproject.firebaseapp.com',
    storageBucket: 'irischatproject.firebasestorage.app',
  );
}
